---
title: "ESM244 Assignment 1"
author: "Kelsie Fronheiser"
date: "1/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Part 1
```{r}
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

#for PCA
library(ggfortify)

#for ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

#to make compound figures:
library(patchwork)
```

```{r}
sierra_herps <- read_excel("sierra_amphibians.xlsx")
```
#### Graph 1
```{r}
sierra_herps_tidy <- sierra_herps %>%
  filter(amphibian_species == "RAMU") %>%
  filter(amphibian_life_stage %in% c("Adult", "SubAdult", "Tadpole")) %>% 
  mutate(date = year(survey_date))
         
sierra_herps_totals <- sierra_herps_tidy %>% 
  group_by(date) %>% 
  summarise(sum = sum(amphibian_number))

sierra_graph1 <- ggplot(data = sierra_herps_tidy, aes(x = date, y = amphibian_number)) +
  geom_col(aes(fill = amphibian_life_stage))

```


#### Graph 2
```{r}
sierra_herps_tidy2 <- sierra_herps %>%
  filter(amphibian_species == "RAMU") %>%
  filter(amphibian_life_stage %in% c("Adult", "SubAdult")) %>% 
  group_by(lake_id) %>% 
  summarise(sum = sum(amphibian_number)) %>% 
  filter(sum > 1318) %>% 
  mutate(lake_id = paste("Lake",
                         lake_id, sep = " "))
  

sierra_graph2 <- ggplot(data = sierra_herps_tidy2, aes(x = reorder(lake_id, -sum), y = sum)) +
  geom_col(aes(fill = lake_id)) +
  labs(fill ="Lake ID Number")
```

```{r}

graph_combo <- (sierra_graph1 / sierra_graph2) & theme_minimal() &
  plot_annotation(title = "Endangered Mountain Yellow-Legged Frogs in the Sierra Lakes",caption = "These two graphs display the abundance of endangered Mountain yellow-legged frogs located in the Sierra Nevadas.\n The top graph shows the total abundance in each year by life stage. The lower graph shows the total number of adult \n and subadult Mountain yellow-legged  frogs in each of the five Sierra Nevada Lakes with the highest abundance \n of these frogs. ")

graph_combo
```

## Part 2
```{r}

```








